### ISSUE TITLE
Rails 4.1.5 + jquery2 couldn't find file 'jquery2'

### ISSUE THREAD

**Issue by edjarris** [rails/jquery-rails#171]
Hello,

I'm using rails 4.1.5 and I want to force to use jquery 2.1.1 version. I folow the readme instructions and i change in my application.js:

<pre>
//= require jquery2
//= require jquery_ujs
</pre>

I'm usign gem 'jquery-rails', '3.1.2'.

I restart server and i get the error "couldn't find file 'jquery2'".

Anything will help, thanks in advance!

**Comment by jaketlarson** [comment]
I'm getting this too. Requiring jquery was working fine, but jquery2 was not. I couldn't figure it out on two different apps, so I just switched to a CDN for jQuery.
