### ISSUE TITLE
can't find file 'jquery' (windows)

### ISSUE THREAD

**Issue by s0nspark** [rails/jquery-rails#186]
I have started a new rails 4.2.0 app with jquery-rails 4.0.3 and am getting the Sprockets::FileNotFound exception when running my app because it can't find jquery... where should I look for the cause? 

I'll be happy to provide configs, etc, if they will be helpful but this is pretty much just straight out of the box at this point.

... and, yeah, I know... Windows *sigh*

**Comment by rafaelfranca** [comment]
I don't have a windows machine to test it, so I can't help with this issue. Maybe it is related with file permission of the generated gem?

**Comment by s0nspark** [comment]
File perms should not be any kind of issue - I am admin on the machine. I will look into it, though, and report back.

Forgive my ignorance here but is the "magic" of this gem really just that it vendors jquery for inclusion in the asset pipeline so you don't have to manage jquery manually? I'm just trying to think through what is happening (or isn't in this case *grin*)

**Comment by rafaelfranca** [comment]
> vendors jquery for inclusion in the asset pipeline so you don't have to manage jquery manually?

yes, it is.

**Comment by s0nspark** [comment]
OK - thanks :)

I checked perms and they are wide open so I guess we can chalk this up to rails+Windows weirdness.

**Comment by rafaelfranca** [comment]
Indeed, a lot weird. Even more that this is the first report of this problem.

**Comment by s0nspark** [comment]
Closing this ... I found the issue. Somehow jquery-rails got edited out of my Gemfile, hence it wasn't being loaded. 

__:facepalm:__  

Sometimes it is the little things. ;-)
