### ISSUE TITLE
jQuery 2, railties 4.2 dependency

### ISSUE THREAD

**Issue by aTei** [rails/jquery-rails#187]
Hello. Looks like I missing something, but `jquery-rails 4.0.3` (which has jQuery 2) depends on `railties >= 4.2.0`. `Rails 4.0.13` and `rails 4.1.9` depends on  is `railties` that is below `4.2`. 

So there is no way to use jQuery 2 via `jquery-rails` right now except updating to `rails 4.2.0`.  Am I right? If yes, maybe there's point in changing dependency to more softer `railties 4.0.x`?

**Comment by rafaelfranca** [comment]
Yes, it only works with rails 4.2. And no we can't change the dependency since it will not work with versions less than 4.2

**Comment by sambao21** [comment]
@rafaelfranca what's the reason for the railties 4.2 dependency? i.e. what in railties 4.2 was necessary?  not asking for it to change, just wanted to understand the context better.

**Comment by rafaelfranca** [comment]
The reason is:

The assertions included on this gem depends on code that only exists on Rails 4.2

**Comment by jjb** [comment]
I believe folks are wondering what those assertions are :)

**Comment by rafaelfranca** [comment]
https://github.com/rails/jquery-rails/blob/master/lib/jquery/assert_select.rb#L54
