### ISSUE TITLE
Upgrade needed to jquery-ui 1.11.4

### ISSUE THREAD

**Issue by ariroseonline** [rails/jquery-rails#189]
`$( "#sortable" ).sortable();` returns "undefined is not a function" using any jquery version as a dependency, the jquery-rails gem, and  `//= require jquery-ui`.

If I manually include jquery-ui 1.11.4, everything works. I suspect there is a breaking change between jquery-ui 1.11.2 (which the this gem currently uses) and jquery-ui 1.11.4

**Comment by udaykadaboina** [comment]
Have you included `gem 'jquery-ui-rails'` in your gemfile in the first approach?

**Comment by rafaelfranca** [comment]
jquery-ui is not included anymore with this gem.

**Comment by rafaelfranca** [comment]
Use jquery-ui-rails
