### ISSUE TITLE
Remove CSRF Token on Cross Domain Requests

### ISSUE THREAD

**Issue by ideasasylum** [rails/jquery-rails#202]
Background: I'm trying to make a cross domain ajax request to the Wistia api which (rightly) rejects the `X-CSRF-Token` header.

jquery-ujs uses a prefilter to set the CSRF token header but only for non-`crossDomain` requests. 
```javascript
 $.ajaxPrefilter(function(options, originalOptions, xhr){ if ( !options.crossDomain ) { rails.CSRFProtection(xhr); }});
```
https://github.com/rails/jquery-rails/blob/master/vendor/assets/javascripts/jquery_ujs.js#L342

So far, so good. If I make a local ajax request, the CSRF header get set correctly. 

Now, if I make a `crossDomain` request, `rails.CSRFProtection` will not be executed… **but** *the header will already be set from the previous invocation and it isn't cleared*

I solved this by adding my own prefilter to explicitly remove the header for crossDomain requests

```javascript
$.ajaxPrefilter(function(options, originalOptions, xhr){
  if (options.crossDomain) {
    delete options.headers["X-CSRF-Token"]
  }
});
```

I'm still not 100% sure why the header is persisting between requests though.

Are there any tests for this functionality that I can verify this problem is general and not specific to my app?

**Comment by rafaelfranca** [comment]
You can try to see the jquery-ujs tests (it is where this feature is implemented)

**Comment by rafaelfranca** [comment]
Closing this issue because it is stale
