### ISSUE TITLE
Any way to avoid duplication between git repos

### ISSUE THREAD

**Issue by justin808** [rails/jquery-rails#205]
I noticed that the jquery-ujs is in 2 places on github:

* https://github.com/rails/jquery-rails/blob/master/vendor/assets/javascripts/jquery_ujs.js
* https://github.com/rails/jquery-ujs/blob/master/src/rails.js

* How are these kept in sync?
* Are there advantages (or necessities) doing it this way?
* In the long term, should the duplication be avoided, and maybe jquery-rails could refer to the version number?

**Comment by rafaelfranca** [comment]
One is the source code other is the packaged version.

> How are these kept in sync?

They don't need to. Only when we need to release a new version of jquery-rails https://github.com/rails/jquery-rails/blob/04fcfa29b859eef9479f89b6a799d00212902385/Rakefile#L53-L57.

> Are there advantages (or necessities) doing it this way?

We decouple the development of jquery-rails and jquery-ujs. So we don't need to have things like upgrading jquery version on the jquery-ujs repository.

> In the long term, should the duplication be avoided, and maybe jquery-rails could refer to the version number?

I don't see why. It already refer to the version number.
