### ISSUE TITLE
changes to Versions.md didin't get merged back into master?

### ISSUE THREAD

**Issue by jjb** [rails/jquery-rails#206]
Looks like the info for 3.1.4 here: https://github.com/rails/jquery-rails/blob/v3.1.4/VERSIONS.md

Is not in master: https://github.com/rails/jquery-rails/blob/master/VERSIONS.md

Maybe this is expected but just pointing it out just in case...

**Comment by rafaelfranca** [comment]
Yes, it is expected. For 3.1.x versions please look at the 3-1-stable branch. https://github.com/rails/jquery-rails/tree/3-1-stable.
