### ISSUE TITLE
Doesn't work with gem 'jquery-datatables-rails'

### ISSUE THREAD

**Issue by burtondav** [rails/jquery-rails#208]
I'm getting the error "Uncaught TypeError: Cannot use 'in' operator to search for 'length' in isArraylike @ jquery.self-". 

It happens in these lines:

    var length = "length" in obj && obj.length,
    		type = jQuery.type( obj );

    	if ( type === "function" || jQuery.isWindow( obj ) ) {
    		return false;
    	}

This stackoverflow question states that "The versions 1.11.3 and 2.1.4 have this issue."

Jquery-rails versions, say:

    module Jquery   
        module Rails     
          VERSION = "4.0.5"     
          JQUERY_VERSION = "1.11.3"     
          JQUERY_2_VERSION = "2.1.4"     
          JQUERY_UJS_VERSION = "1.1.0"   
        end
     end

How can I use different versions of Jquery?

**Comment by rafaelfranca** [comment]
You can see the versions table here https://github.com/rails/jquery-rails/blob/master/VERSIONS.md#bundled-versions. But if you plugin doesn't work with latest jQuery you should open an issue there and ask them to fix it.
