### ISSUE TITLE
jQuery defaults to 2.2.1

### ISSUE THREAD

**Issue by rhymes** [rails/jquery-rails#219]
In my application.js (and active_admin.js) the line

//= require jquery

results in the inclusion of /assets/jquery/dist/jquery.js which is jQuery 2.2.1 instead of jQuery 1.12.1, 

![screen shot 2016-03-17 at 10 44 29 am](https://cloud.githubusercontent.com/assets/146201/13842224/5accc6ca-ec2d-11e5-9f12-f75d380f0382.png)

how can I include the older jQuery?

Rails 4.2.6
jquery-rails 4.1.1

**Comment by rafaelfranca** [comment]
Seems like your application have more than one jquery in the assets load path. jquery-rails provides a file inside `vendor/assets/javascript` so the fact that `assets/jquery/dist/jquery.js` is being included means that it is not a jquery-rails issue.

**Comment by rhymes** [comment]
@rafaelfranca thanks! I had another version of jQuery with bower for the frontend. I removed that and now everything is correct.
