### ISSUE TITLE
jQuery 3.0.0 has been released

### ISSUE THREAD

**Issue by connorshea** [rails/jquery-rails#223]
http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

**Comment by Sega100500** [comment]
Please upgrade gem to use jQuery 3

**Comment by bodrovis** [comment]
Btw,  note that now a "slim" version of jQuery is also available:

> All in all, it excludes ajax, effects, and currently deprecated code. The size of jQuery is very rarely a load performance concern these days, but the slim build is about 6k gzipped bytes smaller than the regular version – 23.6k vs 30k

**Comment by cannikin** [comment]
Well, I added 3.0.0 and was about to create a pull request, but I read the contribution guidelines and for security reasons they can't accept pull requests that include new versions of the JS files. But, if anyone needs to use 3.0.0 in an emergency (and trusts me!) you can get my version here: https://github.com/cannikin/jquery-rails and use the `jquery-3` branch.

**Comment by bodrovis** [comment]
@cannikin :cool:

**Comment by connorshea** [comment]
@cannikin you can probably open an MR with the scaffolding, and then they can merge it and add the actual jQuery library itself.

**Comment by cannikin** [comment]
@connorshea Oooo, good call. I'll make one with empty JS files and they can copy/paste the actual code in there whenever someone gets the chance.

**Comment by cannikin** [comment]
Done! #224

**Comment by usbsnowcrash** [comment]
Is there anything I can do to help get #224 merged in?

**Comment by Sega100500** [comment]
When support for jQuery 3 will be added to official release of jquery-rails gem ?

**Comment by connorshea** [comment]
@rafaelfranca sorry to bother you, but could you check this out or assign a core member to it?

(Thank you for maintaining Rails over the past few years, you've been awesome ❤️)

**Comment by Sega100500** [comment]
@rafaelfranca 
```gem update``` , ```bundle update``` has no effect
In Gemfile.lock still ```jquery-rails (4.1.1)```
Please update in global repository
