### ISSUE TITLE
JQuery 3 not included in gem

### ISSUE THREAD

**Issue by lmcgrath** [rails/jquery-rails#227]
I just tried out this gem and followed the instructions, but I got the following error for `//= require jquery3`

`couldn't find file 'jquery3' with type 'application/javascript'`

Doesn't look like JQuery 3 is actually in the gem: https://github.com/rails/jquery-rails/tree/e47edc6e2abc129aee371ca4d3dbb386fe9acb9a/vendor/assets/javascripts

**Comment by rafaelfranca** [comment]
Fixed on master

**Comment by boardfish** [comment]
Still getting this error. Rails 5.1.3, jquery-rails 4.3.1.
