### ISSUE TITLE
Missing delegate event 

### ISSUE THREAD

**Issue by honeypc** [rails/jquery-rails#229]
The function "delegate" not binding event to "linkClickSelector" when I using: 

 <% @list.each do |item| %>
//todo
 <%= link_to glyphicon("trash", "Disable"), { :action => 'delete', :id => 1 }, :confirm => 'Are you sure?', :method => :post %>
<% end %>

I have tried copy all $document.delegate into  $document.ready it work fine. Let me know any solution for fix that
 My jquery library version 1.7.1

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?
