### ISSUE TITLE
still 1.12.4 version with "require jquery3" in application.js

### ISSUE THREAD

**Issue by chdem** [rails/jquery-rails#234]
Hello,

In the js console responding :
`jQuery.fn.jquery
"1.12.4"`

Here my app/assets/javascripts/application.js :
`//= require jquery3
//= require jquery_ujs
//= require turbolinks
//= require_tree .
//= require jquery-ui
//= require bootstrap-sprockets`

Is there any error there ?
Thank you.

**Comment by rafaelfranca** [comment]
As you can see here https://github.com/rails/jquery-rails/blob/master/vendor/assets/javascripts/jquery3.js#L3 the version of the jquery3 file is 3.1.0. So if it is not the right version in your application it must be something in your application. Looking the code you posted I don't see anything wrong. Make sure you have only one jquery file in your project.
