### ISSUE TITLE
Update jQuery to 1.12.4 on the 3.1 branch

### ISSUE THREAD

**Issue by choilive** [rails/jquery-rails#254]
I have a legacy rails 3.2 app that I want to upgrade to jquery 1.12.4 and jquery-rails 4.X.X is incompatible. 

Is there any possibility of a 3.1.4 with jquery 1.12.4? 

Would submit a PR for it, but it looks like the contrib guidelines won't accept PRs with updated jquery scripts.

**Comment by rafaelfranca** [comment]
Done.
