### ISSUE TITLE
Issues with JQuery mobile

### ISSUE THREAD

**Issue by knzudgt** [rails/jquery-rails#257]
I am using jquery-rails 4.1.1 in a rails 5.0.0.1 application.
I am wondering if there are any issues between jquery-rails 4.1.1 and jquery mobile version 1.4.5, because once included jquery mobile in my application everything started to fall apart: css rules are not respected, redirects fails, javascripts do not work.

**Comment by rafaelfranca** [comment]
Thank for the issue. It should not. jquery-rails only include the regular jQuery. If there is incompatibility between them this is a jQuery issue given this gem only package jQuery
