### ISSUE TITLE
How to point to 1.12.3 ?

### ISSUE THREAD

**Issue by lafeber** [rails/jquery-rails#260]
I've checked the https://github.com/rails/jquery-rails/blob/master/VERSIONS.md file but there's no way to get 1.12.3 using this gem? 

The reason I'm asking: according to https://snyk.io/vuln/npm:jquery?lh=1.12.4 there's a vulnerability in 1.12.4

**Comment by rafaelfranca** [comment]
Is not the vulnerability also present in 1.12.3? According to that website it is

**Comment by lafeber** [comment]
Hmm, you're right. Should probably be 1.12.2... Anyways, we decided to upgraded to jquery3 - which is something everyone should do I suppose. Thanks for answering!
