### ISSUE TITLE
jQuery 3.4 released. Please upgrade gem

### ISSUE THREAD

**Issue by mtmail** [rails/jquery-rails#261]
README.md asks for opening an issue, not submitting a PR so I'll keep it short. Thanks a lot

https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/

**Comment by blshkv** [comment]
please make it your high priority due to the following security vulnerability:
https://snyk.io/blog/after-three-years-of-silence-a-new-jquery-prototype-pollution-vulnerability-emerges-once-again/

**Comment by kstratis** [comment]
For the record [jQuery v3.4.1](https://blog.jquery.com/2019/05/01/jquery-3-4-1-triggering-focus-events-in-ie-and-finding-root-elements-in-ios-10/) has been released.

**Comment by OlivierGrimard** [comment]
+1

**Comment by rossinkiwi** [comment]
It would be great if this gem could be updated due to potential security vulneribility [https://www.zdnet.com/article/popular-jquery-javascript-library-impacted-by-prototype-pollution-flaw/](url)

**Comment by blshkv** [comment]
@rossinskiwi  Please read before commenting

**Comment by felix91gr** [comment]
Will this be fixed? We're working with this gem in a public project, and it's kind of problematic to be opening up our users to security holes.

**Comment by rafaelfranca** [comment]
4.3.4 and 4.3.5 released with jquery 3.4
