### ISSUE TITLE
gem jquery or jquery-rails?

### ISSUE THREAD

**Issue by ndvbd** [rails/jquery-rails#262]
I have jquery-rails in my Gemfile which enable me to have jquery 1.12. I want to upgrade jquery. 
However, when I do
gem 'jquery2'
and then do 
bundle install 
I get
Could not find gem 'jquery2' in any of the gem sources listed in your Gemfile.

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by ndvbd** [comment]
Thanks. Saw that I need to replace jquery->jquery2 in the .js file
