### ISSUE TITLE
Setup bundle to install only JQuery 3

### ISSUE THREAD

**Issue by ghraka** [rails/jquery-rails#265]
Hi Everyone, I have a question. So when using jquery-rails gem, is there any way to ignore JQuery version 1.x.x ? To give more context, some security scan applications are flagging JQuery 1.12.4 having cross site scripting vulnerability. So is there a way for jquery-rails gem to install only 3.4.1?

**Comment by rafaelfranca** [comment]
No. It will always install all versions.
