### ISSUE TITLE
Security issue with jquery 3.4.1

### ISSUE THREAD

**Issue by laventillelion** [rails/jquery-rails#273]
Please update the included jquery because of the security issue with 3.4.1 https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

Security Fix
The main change in this release is a security fix, and it’s possible you will need to change your own code to adapt. Here’s why: jQuery used a regex in its jQuery.htmlPrefilter method to ensure that all closing tags were XHTML-compliant when passed to methods. For example, this prefilter ensured that a call like jQuery("<div class='hot' />") is actually converted to jQuery("<div class='hot'></div>"). Recently, an issue was reported that demonstrated the regex could introduce a cross-site scripting (XSS) vulnerability.

**Comment by thenathanjones** [comment]
This would be really great to get a response to, even if it's an ETA so we can plan around it.

**Comment by jrochkind** [comment]
For others who find this, the [Github security advisory](https://github.com/advisories/GHSA-jpcq-cgw6-v4j6) includes a notice of this workaround, for those stuck on an older JQuery version. I'm not sure where Github got this workaround, I don't see the exact suggestion in any of the linked JQuery notices. 

> Workarounds
>
> To workaround the issue without upgrading, adding the following to your code:
>
>     jQuery.htmlPrefilter = function( html ) {
>	     return html;
>     };
>
> You need to use at least jQuery 1.12/2.2 or newer to be able to apply this workaround.

I'm still a bit disturbed that the maintainers of this jquery-rails repo (if any?) haven't commented in 12 days since filing, on a security vulnerability issue.

**Comment by jrochkind** [comment]
Note also 3.5.1 is released fixing a regression with 3.5.0. 

https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/

Someone might try to prepare a PR to update jquery in jquery-rails, if they got any response/encouragement from maintainers that such a PR might be reviewed/merged....

**Comment by thenathanjones** [comment]
> Someone might try to prepare a PR to update jquery in jquery-rails, if they got any response/encouragement from maintainers that such a PR might be reviewed/merged....

First thing I tried to make it easy but they don't accept PRs that update jQuery. Which would be fine if this issue wasn't just sitting here without a response.

**Comment by scicco** [comment]
any ETA to see jquery version bumped?

**Comment by carlosantoniodasilva** [comment]
Released v4.4.0 with jQuery 3.5.1.

https://github.com/rails/jquery-rails/commit/a8b003d726522cf663611c114d8f0e79abf8d200

**Comment by rafaelfranca** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
