### ISSUE TITLE
Update jQuery to v3.6.0

### ISSUE THREAD

**Issue by kstratis** [rails/jquery-rails#280]
Since [jQuery v3.6.0](http://blog.jquery.com/2021/03/02/jquery-3-6-0-released/) was released, I think an update in due.

**Comment by DonikaV** [comment]
Will be great!

**Comment by sonalib-a4** [comment]
It's been 3 months now jQuery 3.6.0 released. Need support in rails

**Comment by elsilentforce** [comment]
Hello guys!
I would really like to have jQuery 3.6.0 support in Rails too.
Apparently, there are no breaking changes from 3.5.1 to 3.6.0
@carlosantoniodasilva can we ask your help to update the library? 🙏

**Comment by carlosantoniodasilva** [comment]
Took me long enough :D, v4.5.0 with jQuery 3.6.0 is out.
