### ISSUE TITLE
Update `jquery-rails` to include new jquery-ujs for better Turbo compatibility

### ISSUE THREAD

**Issue by ericstewart** [rails/jquery-rails#284]
Last week a new version of jquery-ujs was released to allow proper coexistence with forms written to use Turbo from Hotwire. Can we get a release that includes this update to rails-ujs for those of us still using the asset pipeline?

See https://github.com/rails/jquery-ujs/pull/521 and https://github.com/rails/rails/pull/42476

**Comment by carlosantoniodasilva** [comment]
Release v4.5.1 with updated jquery-ujs, thanks.
