### ISSUE TITLE
JQuery 3.6.1 released

### ISSUE THREAD

**Issue by ritikesh** [rails/jquery-rails#288]
Looks like JQuery 3.6.1 has been [released](https://blog.jquery.com/2022/08/26/jquery-3-6-1-maintenance-release/) with an important [bugfix](https://github.com/jquery/jquery/issues/4867). Can we please update the release in this gem as well? I was considering raising a PR, but noticed this in the contributing guidelines, so opening up the issue instead. TIA!
> However, for security reasons, we won't be accepting pull requests with updated jQuery scripts.

**Comment by carlosantoniodasilva** [comment]
Released v4.5.1 with updated jQuery version, thanks.
