### ISSUE TITLE
What is the status of v4.5.1 ?

### ISSUE THREAD

**Issue by kohbis** [rails/jquery-rails#290]
Hi, Thank you for your maintenance.

New version `v4.5.1` was tagged at https://github.com/rails/jquery-rails/commit/de8792d63210003c2bdbd973ee0b3a1d977b4a67 (I found this on Dependabot)
But [CI failed](https://travis-ci.org/github/rails/jquery-rails/builds/774840463) and [CHANGELOG](https://github.com/rails/jquery-rails/blob/7e6f508b36b4ba7341a9f742d864c84a5b6bb626/CHANGELOG.md) says `unreleased` .

Is there still work left for `v4.5.1` ? 
Or is the documentation just not updated?

**Comment by carlosantoniodasilva** [comment]
I just missed updating the version in changelog, it's released and all good.
