### ISSUE TITLE
JQuery 3.7.0 released

### ISSUE THREAD

**Issue by ritikesh** [rails/jquery-rails#297]
Looks like JQuery 3.7.0 has been [released](https://blog.jquery.com/2023/05/11/jquery-3-7-0-released-staying-in-order/) with an important [bugfix](https://github.com/jquery/jquery/pull/5224). Can we please update the release in this gem as well? TIA.

Some refs - 
https://github.com/select2/select2/issues/5993#issuecomment-1487623523
https://github.com/select2/select2/issues/5993#issuecomment-1544538515

**Comment by diesl** [comment]
Hi @carlosantoniodasilva,

could you please help releasing a new version? 
This would be highly appreciated, because it solves some problems concerning focus/blur events, see mentioned bugfix.

**Comment by diesl** [comment]
Hi @rafaelfranca,

maybe you can help to release a new version? Thanks in advance!

**Comment by diesl** [comment]
Hello again @rafaelfranca,
I see you merged two pull requests last week, would it be possible for you to release a new version, too?

**Comment by carlosantoniodasilva** [comment]
I'm working on it.

**Comment by carlosantoniodasilva** [comment]
v4.6.0 was just released with jQuery v3.7.0.

**Comment by diesl** [comment]
Thanks @carlosantoniodasilva for the new release!

**Comment by ritikesh** [comment]
thanks @carlosantoniodasilva!
